### ISSUE TITLE
some help needed

### ISSUE THREAD

**Issue by Tommie1236** [0x506978656c/Single-BDScord#3]
this is not an really an issue,

i'm trying to set this up on my server. it goes all good until it says "Install the latest release of BDScord" but there are no releases.
how am i supposed to set it up?

**Comment by CachesKCH** [comment]
do a source download with the green "code" button and download as zip. that's what the documentation means when it says "latest release" 
![image](https://user-images.githubusercontent.com/59543366/152698213-de768c06-ebc1-4d5f-9b00-321efc7c85fc.png)

**Comment by Tommie1236** [comment]
thank, that worked
